### ISSUE TITLE
Kleiner als 2 cm Breite funktioniert nicht

### ISSUE THREAD

**Issue by Simon0Harms** [JokerGermany/VIT-Roboter-Challenge#4]
Bisher vermutete mögliche Gründe:
1. Die Toleranz muss angepasst werden.
2. Die verschobene Grenze wenn weiß erkannt wird muss angepasst werden.

**Comment by JokerGermany** [comment]
Sollte das gleiche Problem wie #2 sein

**Comment by Simon0Harms** [comment]
Sollte das gleiche Problem wie #2 sein
